### ISSUE TITLE
Ouvrir le port 3000 de Chacana afin de pouvoir accéder au backend depuis Internet

### ISSUE THREAD

**Issue by seza443** [GeoHealth/HAppi_backend#14]

**Comment by seza443** [comment]
Mail envoyé

Ce ne sera sans doute *pas* accessible depuis Internet mais uniquement depuis l'intérieur du réseau UCL

**Comment by seza443** [comment]
Port ouvert uniquement au sein du réseau UCL

**Comment by Kagelmacher** [comment]
Finalement nous allons utiliser notre serveur à nous
