### ISSUE TITLE
Ajouter la gem Sidekiq

### ISSUE THREAD

**Issue by seza443** [GeoHealth/HAppi_backend#34]
http://sidekiq.org/

Ajouter la gem et comprendre son fonctionnement, ce qu'elle permet de faire et comment le faire.

**Comment by Kagelmacher** [comment]
Utile pour envoyer les mails aux docteurs mais pourrait être utilise pour d'autres process.

**Comment by seza443** [comment]
- [ ] Install Redis local
- [ ] Redis on SIMUL environment
- [ ] Redis on TEST environment
- [ ] Redis on MASTER environment
