### ISSUE TITLE
Install the backend on ingi computer (#Chacana)

### ISSUE THREAD

**Issue by Kagelmacher** [GeoHealth/HAppi_backend#4]
- [ ] [Flynn](https://flynn.io/)
- [x] PostgreSQL
- [x] (Rails ?)
- [ ] Ouvrir un port

**Comment by seza443** [comment]
Finalement il s'appelle *chacana.info.ucl.ac.be*

**Comment by seza443** [comment]
Pas possible d'installer flynn sur centos ? https://github.com/flynn/flynn/issues/1791

**Comment by seza443** [comment]
@mlainez Nous n'avons pas su installer Flynn sur CentOS. Une idée d'alternative ?

**Comment by seza443** [comment]
J'ai déployé le backend "à la main" pour le moment

**Comment by seza443** [comment]
Dokku est installé correctement

**Comment by seza443** [comment]
Nous avons commandé une instance VPS chez OVH afin d'avoir Ubuntu, une IP fixe, des ports ouverts à tout le monde.
