### ISSUE TITLE
Récupérer les conditions météo grâce à la position et la date de l'occurrence

### ISSUE THREAD

**Issue by Kagelmacher** [GeoHealth/HAppi_backend#40]

**Comment by seza443** [comment]
@Kagelmacher ce serait cool d'utiliser Sidekiq #34 pour ça.
Comme ça, le backend répond à l'app mobile dès que l'occurrence est ajoutée.
Et ensuite, en asynchrone, Sidekiq récupère les conditions météorologiques et les lient à l'occurrence.

**Comment by Kagelmacher** [comment]
http://status.darksky.net/

**Comment by Kagelmacher** [comment]
Il ne reste plus qu'à écrire les tests avec Sidekiq

**Comment by seza443** [comment]
https://github.com/philostler/rspec-sidekiq

https://github.com/mperham/sidekiq/wiki/Testing

**Comment by seza443** [comment]
qualité de l'air?

**Comment by seza443** [comment]
@Kagelmacher cette carte peut etre fermée si la coverage est à 100%
